[package]
name = "cfg"
version = "0.1.0"
edition = "2024"

[dependencies]
oxc_allocator = "0.89.0"
oxc_ast = "0.89.0"
oxc_cfg = "0.89.0"
oxc_parser = "0.89.0"
oxc_semantic = {version = "0.89.0", features=["cfg"]}
oxc_span = "0.89.0"
rustc-hash = "2.1.1"

[features]
cfg = []
