[package]
name = "aya-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-common = { path = "../aya-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "aya"
path = "src/main.rs"
